apiVersion: v1
kind: Secret
metadata:
  name: sigrun-tls
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMwekNDQWJzQ0ZHQTV1UDZVUUhPRGhqOTlqNS82RHlzVVNXbjJNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1DOHgKTFRBckJnTlZCQU1NSkVGa2JXbHpjMmx2YmlCRGIyNTBjbTlzYkdWeUlGZGxZbWh2YjJzZ1JHVnRieUJEUVRBZQpGdzB5TVRBNE1EWXhOekF4TlRCYUZ3MHlNVEE1TURVeE56QXhOVEJhTUIweEd6QVpCZ05WQkFNTUVuTnBaM0oxCmJpNWtaV1poZFd4MExuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFLTHEKaXh5dFV4VTZaV2VkT01SVDZtelRZL3piazFieXJCOVRBRHpqQndsZ0FLeXhwMVFsVG5sck5jUDQ2VDkxMXFrZApVTFE0RG9UUjhMU0g0TnVjQ1ZjdUZUNk1pdlB2TFdDUGVMei9FQThILzlCclgzcDVlSmhPREZUUDI4R1dKYndjCnRXckJnSk1HYUVyRlBJd2l3dmRzajRPZXExV2xVOUtoUTlraTBMZVA4U1dKKzNTS2VkSHNNckI4WnRCaHFtcXIKUXdzNlY2Q0g5Vkh6ZTRQdUhsUVZ0Y0pxYWc2RzBkSnJXa1QvZWRobFlxSGdsUC9vaGRNWVRIdWpOcjBEeHNLMQp2cThsazIvSWEzcTB6WmJkcVVxUVV5eEtTekRULzRrS29HcS9VWndmRmJVQ3F3TG1Qa0k3VUp0bFVuTDJaeG5aCjJOcSthRW5laUNZTGlVOVlHckVDQXdFQUFUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUF5R053NU1ZU205aDkKVW01aFpyeUgwZ2M0WmhVekJWamp3a1Nibk5WRkZyKzN2dnBJL3A3Y3FOVTlCeStycFgyQ0lxTnhHenBUcVN4bwpQNyt3SDF4K3pPemFKZXhoZDZwOUJFcG40cXNWT28vdXMzRTdheWR0WmxHL3pDc20waG8yVTZ1ODVXMXYybUdjCnNGZjc3TlZTOGZjbUtCSHNWSW96MW1mS0tLN2U5M1hqdElZM2pid3g3d2gwSzg1ZlkrWHNLb0JCZGtiNjVKVjMKeEcwVXhaVHlBMnVoRUFoNXUxVDNMS3pqZStXZEpHbXVITjlyQmt4M1B2TUxZV0NDTmtVU0psdzJ3cHRLRE9wVgpzNlhXYVpyRXhnOVBmZ1dENE5CL0ZCbW1VWmt4UFhEWGsvcmtESTN2R3FVdHMzL2Voa2NEblVMSTFYMDhnQSs5CmNxdXg2WDVSSXc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBb3VxTEhLMVRGVHBsWjUwNHhGUHFiTk5qL051VFZ2S3NIMU1BUE9NSENXQUFyTEduClZDVk9lV3Mxdy9qcFAzWFdxUjFRdERnT2hOSHd0SWZnMjV3SlZ5NFZQb3lLOCs4dFlJOTR2UDhRRHdmLzBHdGYKZW5sNG1FNE1WTS9id1pZbHZCeTFhc0dBa3dab1NzVThqQ0xDOTJ5UGc1NnJWYVZUMHFGRDJTTFF0NC94SlluNwpkSXA1MGV3eXNIeG0wR0dxYXF0REN6cFhvSWYxVWZON2crNGVWQlcxd21wcURvYlIwbXRhUlA5NTJHVmlvZUNVCi8raUYweGhNZTZNMnZRUEd3clcrcnlXVGI4aHJlclRObHQycFNwQlRMRXBMTU5QL2lRcWdhcjlSbkI4VnRRS3IKQXVZK1FqdFFtMlZTY3ZabkdkblkycjVvU2Q2SUpndUpUMWdhc1FJREFRQUJBb0lCQVFDS3p1b09XZ05qSCtsTQptaUhHN1hUY21sUWtHblgwYkRtSlN1LzE4TDJMR0ZnYXpCYzAwOENFSlh1ZTZSTGJOaXphMUpaeHB4MS92MXltCmhPdHFVZzJIVVVWYWtPYkhwbTcwU2VubXBpL3BqcmhBdld1UmI3UDNtUEJheHV1SGlzWEYvSFA2YkxwL0NzT0wKaVhmb01xb0pwRjYzRjFjR1Z5SVBZY1hzV1FTYWtOY3dFZmtTSm1jeFB5VUVGR0lCbDJsaGs2NTBTbUg2d01OcgpibVVmK1pDRGdQVjBMdHVoRUVNYk1NUHNVMDJLOHd6L05YRmR2ekQ0VTVvV2hxLzBobzBjTTdOcjFGcG9zcTMwCmtxWTBKZmZRTFdnQ3NWdTVaSlhWVmxCaVNRUUxKVkVWOHFUb0pxK1E5a3NJZEhBMFcrUjBtVmYrUkVUSlpZamYKODc0TXU3NEJBb0dCQU01cXlkZ2RxajcxU2Z3V3YzdnlOSkllZW9PUkxwOUNURnN5WVU5VFZxY09YSkFDR1B2MgpWS0xCOTczL3oycHJVZThuYkhrcHF3WEpPV1gxM0wvd1g2aUYrcVZ5TmN6ZUxkNkU1UStFUUovOGpLbmlUV1pTCnVpSkNMNStGSFVDUCt0NzFiTnVJa2Z0UWYwN1dSK3lFd2h2UFVmb3JqMkI4cWkxeEtZb0JXN0VoQW9HQkFNb00Kd0FndCtFZDY5UDNscGVsWFlLZFBXbi8yTVhORjJBaGZoSm1BNkFHT3Y5S21aQVJWSUVDdVM3TnRQT043UDdZTwpDZzRQSzFzR1RrdWdXVUxUeUJZRy90b0hFRnlwLzMzV3lPQXhPb2xEM2hnWk84TEhEcStnMEdNSEh5OEVLc3ZhCk4rc1hoZ1VDQUZGUFBOK0Jqc2sxc3Y2YjFlQy9NQms3UmZFWEZPZVJBb0dCQUp1YmUxQVZoT3J6UlBQcVBpMzAKOTlhVGJXNVRleDhKL3IvZEtlaC8vZG53QksxM04xaHlhWGxNMmpOOGJlTmV4aVNReHNCTVBpWWRmTXkxWE5YQgpJb3ZMZkpsT2tPcEJMN2tJM0JrbmJRUnVnYWZyOXNkRlpCWkJhTjlMblRLM2w3cU9yNktMd09rQTFRZ2NsNW5nCnR1ZjZFV1dUZ3dHTTJVbHFmcE1QMVF5aEFvR0JBSUJHNkFSSmF6KzJpS1JKa0xROGpWaXJ3TUZOQk1neXA1MXAKUno1TjRQNWNLdDBLVnFXSmhoaUtqL1V5ZlYzUGVmdVRuajZlMHQvUGVSWDZqN0VsMC9wb0pwVTF0dVdkNkY5MApaY1F3ZlFGNDNTQmZwTmxjbDY1Wll2UDhLWWdvRlNPblA2azZIaFEvMlFQR1V0ZHo0YnROSkg4UllSQjNVWW96Clg0eFpJeVNCQW9HQURiKzNIMFBrL1VpeWFOMzRGNzhjVHpQUmdsOXVxZ3A0RDlSMnM4cnloWUptWHd2Q2dDS0wKZndsU3A2VTlNTUlvVmp5dk55TDkyNlFIQnBHVE1YL0RDMHRwWVdnZGN4Sk1qZHg5RU5hWmhSdFpzb2xSKyt3dgpCUkRrQzhDSUtmdGp5bWpNZGU0Z1NoYmZyeW9MMEdnZThhNzBDVTYzSHFKeEZ0ZWFoUEVzMkpRPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Service
metadata:
  name: sigrun
  namespace: default
  labels:
    name: sigrun
spec:
  ports:
    - name: sigrun
      port: 443
      targetPort: 8080
  selector:
    name: sigrun
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigrun
  namespace: default
  labels:
    name: sigrun
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sigrun
  template:
    metadata:
      name: sigrun
      labels:
        name: sigrun
    spec:
      containers:
        - name: sigrun-controller
          image: shravanss/sigrun-controller:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: sigrun-tls
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: sigrun
webhooks:
  - name: sigrun.default.svc
    clientConfig:
      service:
        name: sigrun
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVWDJ4VmpOSWlGT0NrOGoyUXdYY1JadmxQRXJnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXhNRGd3TmpFM01ERTFNRm9YRFRJeE1Ea3dOVEUzTURFMU1Gb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQTFQYjhVc2Y3YmpGSGdZaXlqa2tPbm9ab1RIYUpVZm9mM1JzZgp2Q1hzNzZXUWU0Tm02a3lCK3RZRjlhdEdDQmRPVWxWU3p6K0R1WVVwSXM4VkwwMENwTFc1V3dzK1NpTERvbGRuCjZoTStjV1N6VnFwZGV0czljM0pwd0g3TWluMVRPajJjV2pyd25LUndHRGhhMXNyUGl3anZMSE9TZTFKTmRoOEkKSjJiWjA1SzZCcWJoOFpad0d2MjVYanRNdXhEdkNsay9nbFZiajRQOHYwaHg1bFRMY2FOKzhhTGJESVljTDhTTApOZWxKQjFDbGZXT25XQi9XM3BBT0NRTUpELzRuMmRteFBZV0lzVmVYRC9YTEw3RGNNV3dkcmUxditOMEVQMU5mClEvdDk0YmRjMExpMGJyNWUzVHB0WVBLQUFyY1Zoa3ZLODJsWEU4R1hMcUYzN3NoYzN3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVYmJPQ3M2VnZXNElFMmZDdmVnRnppTXRHdlhnd0h3WURWUjBqQkJnd0ZvQVViYk9DczZWdgpXNElFMmZDdmVnRnppTXRHdlhnd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFkbmZ4UGE3TjFWb294bGU3TkRlUzhCT0ZIdjdCMWQ3T3h6eHRaZldsamtTYWtmNjJKSHEybmkrTVpDdEsKODdsMkhmQ1R6NU5yWC9iTVRkNDRtSVFLRWp1SGh2b0VrMmN3Y1Z2Wk0vejc0RGVtbkp0VTJrUWMxYm42YkpudApvdGlrK1oxWGx1dXA0VGZaMmh4N1lHY1NpZU9MS2lNcGszcHZzSEdqVW44RWljcHV1ZXJycjNHYjdleGtsTitxCnVFbGFGNjRLS3RDZXNCNC9HREdzVnhsM1g5MGgrNnhVZHRKYW9aM2M3aTJ1Z1NZYjNMOWN4L1dpUE1pNzhnbnAKUkt0RitFV1hlY0V4ZjROVThUQVdXRHhsdkxrQWVoS0NaODZzNDdnRWNsekhzWElGUjE1VWpPc2JFOG81NXZsSAp2YkUrZkIza2Y4MWhUOHNJMDJrUGhYODlLUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]