apiVersion: v1
kind: Secret
metadata:
  name: sigrun-tls
type: Opaque
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNakNDQWhxZ0F3SUJBZ0lVWURtNC9wUkFjNE9HUDMyUG4vb1BLeFJKYWZrd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXhNRGd3TnpFeU16QXpNMW9YRFRJeE1Ea3dOakV5TXpBek0xb3dIVEViTUJrR0ExVUVBd3dTCmMybG5jblZ1TG1SbFptRjFiSFF1YzNaak1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0MKQVFFQXlIRzVPZU4wQ1N6RWF0OGF3UjEwR244bG5BZi95UGlIRDkwanFoWjQ1eDlvN1BObkpKQ2FtNHQvR3dRSApsTGxGQlRDdGlwdTY2OHpxUGZPb3hkZm0vaVk1OGlyY0dsMVVINDQxQ0VSSGZUaTQ2V3h0cUtGTkZyQnNBdTB3CjR0aVFpdi9ETnNYb3pXaU9XeUNMWHE0ZzlwNEU3b1NmK1Z1ckJkN1lTRi8vSE9LdTZWVmJST2tqelBOSGVLT2UKOXV3T1ZsYUpyNS9TV2dqTzlPNThTdGhveGNDL3V6ajN6Qnk0czRlM3JKcDZmRGNpZzdCbmw4Q0RkVlpHUU5xTgpsMWk5ajBnaHFmK1QrREw3dVZIVkhKU3VEOEc4TVZRWllodDBpdGljNy9Fb0FLK0R0TEVlT0FWL051dmd0ZEltCi9CdFNLVmJHSGUwUnBKUUFVTVU5YSt3OEF3SURBUUFCbzFnd1ZqQUpCZ05WSFJNRUFqQUFNQXNHQTFVZER3UUUKQXdJRjREQWRCZ05WSFNVRUZqQVVCZ2dyQmdFRkJRY0RBZ1lJS3dZQkJRVUhBd0V3SFFZRFZSMFJCQll3RklJUwpjMmxuY25WdUxtUmxabUYxYkhRdWMzWmpNQTBHQ1NxR1NJYjNEUUVCQ3dVQUE0SUJBUUNMdExIeC9NNmlrTGlPCnBVdU8wTm44Rkt5YnEyUXFNMnR6WnNNRXBMYWxWY3pYclFMUHBVU21OdVQwQlo5N1d6S3lCRm85UjhkSXhQTloKZ0lQUytHN2RKTkhKV1duNHltNEdmaTlqQnRnRDMvdi9HOVRRT3ZzS3lQWjN5c0NlWDJZSFVUZlQySGpJUmRiRwpKSWxaV1NISnFXU1hwWUErN2RyR3QyNUh5ZnYwTCt3NXFNQ3F2dkFzY1FBY25PT1ZlRCt3NktFbzE0YVRhS2VSCjlhNmhOakFvQmNJQ2tINlpZVHpLY3RGL1BJRW85WlZVRFNUOGtjT1Q2YzBrZXdsQ202RTZ6MVV1NWxneDJWRkUKYzdpQTlxTHdKR0FTdEV1YWNmUEFIeUZvZFgySCtEWGJVQTMyMEovcUt5aGtUZ2dmWkwzYWV1dG9aSmxxTEpJWAovcTZ3MDY4awotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBeUhHNU9lTjBDU3pFYXQ4YXdSMTBHbjhsbkFmL3lQaUhEOTBqcWhaNDV4OW83UE5uCkpKQ2FtNHQvR3dRSGxMbEZCVEN0aXB1NjY4enFQZk9veGRmbS9pWTU4aXJjR2wxVUg0NDFDRVJIZlRpNDZXeHQKcUtGTkZyQnNBdTB3NHRpUWl2L0ROc1hveldpT1d5Q0xYcTRnOXA0RTdvU2YrVnVyQmQ3WVNGLy9IT0t1NlZWYgpST2tqelBOSGVLT2U5dXdPVmxhSnI1L1NXZ2pPOU81OFN0aG94Y0MvdXpqM3pCeTRzNGUzckpwNmZEY2lnN0JuCmw4Q0RkVlpHUU5xTmwxaTlqMGdocWYrVCtETDd1VkhWSEpTdUQ4RzhNVlFaWWh0MGl0aWM3L0VvQUsrRHRMRWUKT0FWL051dmd0ZEltL0J0U0tWYkdIZTBScEpRQVVNVTlhK3c4QXdJREFRQUJBb0lCQVFDR3ZlUHNwUmpBZmlaLwpUUUM0Sm11QTBFM2c2SU9xZmw2VWJHeG9Edmt4TEswazg2NDNKem0zSy92Q2xsL2VPdmpKdDJKQlZkUStaSjVtCkRPQThOcGxoNlNKMHh4ajBaQjZEbzkzRWM5bTJ0S1dnekRHZTlPZFVSRDRuYlhpNlZTZzlPQmJyUC9qeDg4SVcKUWZkT0t6R2ZkclFML24xbmE1YTR1SWVkaDJKLzhET1RlNnY1TGNmZHFlazd4eG9qRVVqQ0FSQVB0cmVSOFhuRApkSmk5L29kWDc4ZWdRR3pZRTNLdXlZMjNaTENiQmc0SkpuS0c3c2hGTlpKUnY1aHBsWWV1WU5zYlNRRWF5c2d1Ck5mMU1jbVhXSXV5Z21qR2lwclloSnBDYno4blhybmxNY3ZlTzI2cWpKRVZSS3Zwa0VuY2laaWhwcDhqKzA1dTkKSGQvU0tTWkJBb0dCQVB5cVFWSEloaTI3OWRDU1F4UlpwZHI4ODhjaHFJYjMybnE4Q2RkMktpa0I3Q2JoTDNBawpib1FobUUxSWxNNndmSEpsRVVHK0RNbDg5SHAyZmNiTXZXWXpCaG9IbEFHbldvZnZISkMzaXllTkxTTTUzL2lmCkhXanQ2aWM3V1M1RldsaExQLzQ0cENyYkZwQVNxRlFCWDVTK1hLeDJxejlvTUhCbW5uUXFDbC9oQW9HQkFNc1gKQkRBaW1uN3lIalFwejVVeDdyZmRqOTByZTl6MGJnMmdOQTkvbFlFVk1iZzJpbnE4QXQyemh0bmJKa0MrTVJqQgpjTmV2ZnQwRUZJOWcyU2NKWUcyNkpjcXdVRDhRWDhEK2FCU255M2dQbjl4RytLVURaZ2h6NG9zQmpwVE9GU3NSCnlkaVdsYlROdTgxcG82NkJCa1orRHUxNVdZYW4wVkpCc0g1Z3JpaGpBb0dBYTBJblduMkNvSFdUUTRoam00YjMKQm9DdFNCSjh4VmNBVTJ2eHpacW5DU044eVlCOHIrRjNYUFlaL216YVp1ZTYzS0VVODFDbmd2MWRsNE1ubjdZWQpqUU1LQ3hDK2Z2azVVRTFzVmU3a3p0UjZuZUthdHFOdFM3YjcyTTJ6N1JXWjViT0VKZnFMam5uVkdUSWliUTdzCk1XdWlVY0JLc0M4ZHFRbVhLSDhVU21FQ2dZRUFuaXM1enNkVWJlUGhWQnp3RjdGQXl5QWFxRlR5YmI1TWEvNUcKTFgvZkR4NVRqN1dpbWo0Tk9WOVZlaHhzcVdXMjFTSHE0WUJEbkp4TjZ2Q3hqdTZGbEUreW1TNUNBU3VlZDY5cgpuaEtrcThmM1o5WTZWa0hVV0did20vUkZlRzBjSFdRSVFNL2VubWJRaWdWcFBrSXNnZ0F4WGcveGdxYjJwa3FVCnk0ZytleU1DZ1lFQTBkTHBvUCtPTkVMamxuYjVBOXdaQ0l2L0lrUVpUMTVvZStnQ01TZTBJWnpZYVNrV2pYNVMKNkYwUm5PemRwU3FOTWFjeG5FNEgvaVhrMHRoNEhjcGxxUU94YTIrRmJxZkxwSHNKZTR2VlVTcW5mSWdOWisyVwp3ajBFRjVYb3J5Q3A0dVh0UkM0ZHR6WC9LWDV6QUVncmZOLzdhVEdYd1BsS3BNYjYySWcySHR3PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
---
apiVersion: v1
kind: Service
metadata:
  name: sigrun
  namespace: default
  labels:
    name: sigrun
spec:
  ports:
    - name: sigrun-webhook
      port: 443
      targetPort: 8080
    - name: sigrun-controller
      port: 8000
      targetPort: 8000
  selector:
    name: sigrun
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigrun
  namespace: default
  labels:
    name: sigrun
spec:
  replicas: 1
  selector:
    matchLabels:
      name: sigrun
  template:
    metadata:
      name: sigrun
      labels:
        name: sigrun
    spec:
      containers:
        - name: sigrun-controller
          image: shravanss/sigrun-controller:latest
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: sigrun-tls
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: sigrun
webhooks:
  - name: sigrun.default.svc
    clientConfig:
      service:
        name: sigrun
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURQekNDQWllZ0F3SUJBZ0lVU2RWMGpZQ3BmMUtMRVFmczJmZ3BvU2d2VkRnd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0x6RXRNQ3NHQTFVRUF3d2tRV1J0YVhOemFXOXVJRU52Ym5SeWIyeHNaWElnVjJWaWFHOXZheUJFWlcxdgpJRU5CTUI0WERUSXhNRGd3TnpFeU16QXpNMW9YRFRJeE1Ea3dOakV5TXpBek0xb3dMekV0TUNzR0ExVUVBd3drClFXUnRhWE56YVc5dUlFTnZiblJ5YjJ4c1pYSWdWMlZpYUc5dmF5QkVaVzF2SUVOQk1JSUJJakFOQmdrcWhraUcKOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQXVDeHdUVUs2blpuSjk0SEgyZnlhS0ZFbFJsdkY1MFJVMll4NwpkbHJEcnhjS0k0MnovaVM4STZzZU96eUZ4bmliMFBTajVzcHhjZXdjV1g4OWI1NDBkT0F3eFhzR1Y4NEhKVldKCmgxQkhXV2EzbWxjeUhDTE1VVWFEVGYrek1RdG1uV2w4MDkyNHlTdmltOWVoemFoVnR1ZE5ibEZ1YmthNFI2cFkKc3M3THRjN0VkTG9GazJmektHS0pWQVVTVWUvNUlxOGc3Qk5EbmdDY3BrOFE5TVhMZk5INHY2OXZvNWQzMk5NaQplTVlGQTVEOWFXSDhWOFFPVGZmNTBzcWJPUDVOTjdaVWRpNzQ3VXBja0JtMWFsdnlIbWJkb1ZGUCt0QkNGWUJxClpXNmJjL0crUGp3MFdWd3VzTnRmdXJQNEVMK0thdnpjUURhbmdsbmdYdTNiTW9HTGJ3SURBUUFCbzFNd1VUQWQKQmdOVkhRNEVGZ1FVUGRpY3l3WVN2TUFOUGlaM1NaRmZnb0VPL1ZJd0h3WURWUjBqQkJnd0ZvQVVQZGljeXdZUwp2TUFOUGlaM1NaRmZnb0VPL1ZJd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBTkJna3Foa2lHOXcwQkFRc0ZBQU9DCkFRRUFOemNVRGVBTlQzdVdSRFVLQlFNZ3VNbXlYTE16T1E3KzNieThBSHBQbEtPdE1SOU9iMUI1NUsvaDVQVGsKb1VXV3VwcmRqRzIzV01YRVRBUXhNcDl1R09QcXN4RGV6VkVvdWxDR2VrMHNVVktXSXBiNnVUaDh0NmpTdmUyLwpiUTZuY1dLQlZydW1MWC9RSVJlTlZ3S1pFLzNKWEthWS9VM2dLWDJSWnJVbVI2RG9HOWtFQjc1eGZHR1E5cXZ5CkswZFFERFQ4UmdXREdmelNTbkJ6b0F2Qjk5bjhVSlcxdTZVaUVsSFgwSDJHYW5WZDN5cmw3dGIvRTNjZ09uVHAKNTVjNytqVXJYVGlGdDVTRFZTZ2Z6eWpvQnBLQnJDK0Rac09LYzhySUlwK2RLRkwyME05cWovSXNaYVU1MklvawpUalpxcnl2U0k4a1dCM0MrWFV2eUUwQ3ZIUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sigrun-ingress
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: sigrun
                port:
                  number: 8000
---